import SBI
import Helpers
from Helpers import histogram_mode

import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import tqdm
import sys

def ParameterEval_TS(Model, validation_snr, k_fold=5, max_samples=100_000, test_samples=10_000, posterior_samples=500, fidelity=5,maximum_training_epochs = 100):
    """
    Evaluate how the performance of a simulation-based inference (SBI) model
    changes as a function of the number of training samples.

    The function trains the SBI network using progressively larger training
    datasets, evaluates each trained network on a shared test set, and repeats
    the procedure across multiple folds. Performance metrics are collected for
    each training-set size and plotted at the end of the study.

    Parameters
    ----------
    Model : object
        Model used to generate parameters and simulated observations. It must
        provide a ``sample_and_simulation`` method and a ``parameter_list``
        attribute.

    validation_snr : float or array-like
        Signal-to-noise ratio (SNR) used when generating both the training and
        validation/test simulations.

    k_fold : int, optional
        Number of independent training repetitions (folds). Each fold uses a
        different random seed. Default is 5.

    max_samples : int, optional
        Maximum number of simulated training samples generated per fold.
        Must be at least 2000. Default is 100,000.

    test_samples : int, optional
        Number of samples in the shared test dataset used to evaluate every
        trained network. Default is 10,000.

    posterior_samples : int, optional
        Number of posterior samples generated by SBI for each test
        observation. Default is 500.

    fidelity : int, optional
        Number of logarithmically spaced training-set sizes evaluated between
        1,000 and ``max_samples``. Must be at least 2. Default is 5.

    maximum_training_epochs : int, optional
        Maximum number of epochs used to train each SBI network. This value is
        also used as ``stop_after_epochs``. Default is 100.

    Returns
    -------
    kFoldMetrics : list of dict
        Performance metrics for every fold. Each dictionary contains the
        metrics evaluated at each training-set size.

    N : numpy.ndarray
        Array containing the training-set sizes used in the study.

    Raises
    ------
    ValueError
        If ``max_samples`` is smaller than 2000, ``k_fold`` is smaller than 1,
        or ``fidelity`` is smaller than 2.

    Notes
    -----
    A single test dataset is generated using a fixed random seed (2026), so
    all networks are evaluated on the same samples. Each training fold uses
    its own seed (42 + fold).

    The training-set sizes are logarithmically spaced using ``numpy.geomspace``.
    After all folds have been evaluated, ``PlotPerformance`` is called to
    visualize the collected metrics.

    Examples
    --------
    >>> metrics, sample_sizes = ParameterEval_TS(
    ...     Model=model,
    ...     validation_snr=10,
    ...     k_fold=5,
    ...     max_samples=100_000,
    ...     fidelity=5
    ... )
    """

    if max_samples < 2000:
        raise ValueError(f"Max samples is not enough. Received {max_samples}; at least 2000 are required.")

    if k_fold < 1:
        raise ValueError("k_fold must be at least 1")

    if fidelity < 2:
        raise ValueError("fidelity must be at least 2")

    print("~" * 20)
    print("We will perform a study on the number of training samples we might need")

    N = np.unique(np.geomspace(1000, max_samples, fidelity).astype(int))

    # Generate one shared test set
    test_rng = np.random.default_rng(2026)

    Params_test, Signals_test = Model.sample_and_simulation(
        test_samples, parallel=True, rng=test_rng, custom_snr=validation_snr)

    Par_test, Obs_test, _, _ = Helpers.Prep_data(Params_test, Signals_test, Model.parameter_list,Verbose=False)

    kFoldMetrics = []
    for fold in tqdm.tqdm(range(k_fold),desc='Fold Number:',file=sys.stdout):
        train_rng = np.random.default_rng(42 + fold)

        Params_train, Signals_train = Model.sample_and_simulation(
            max_samples, parallel=True, rng=train_rng, custom_snr=Model.snr)

        Par_train, Obs_train, Names, _ = Helpers.Prep_data(Params_train, Signals_train, Model.parameter_list,Verbose=False)

        AllMetrics = {}

        for n_samples in N:
            network = SBI.Train_Network_gpu(
                Par_train[:n_samples], Obs_train[:n_samples],save=False,
                max_num_epochs=maximum_training_epochs, stop_after_epochs=maximum_training_epochs)
            print('\n')
            GuessParams = SBI.Infer(
                network, Obs_test, Num_Samples=posterior_samples,show_tqdm=False)

            Metrics = Performance(
                Par_test, GuessParams, Model)

            for key, value in Metrics.items():
                AllMetrics.setdefault(key, []).append(value)

            del network
            del GuessParams

        kFoldMetrics.append(AllMetrics)

    PlotPerformance(kFoldMetrics, N, Names)

    return kFoldMetrics, N

def ParameterEval_PS(Model, validation_snr, k_fold=5, max_samples=1000, training_samples=10_000, test_samples=10_000, fidelity=5):
    """
    Evaluate how the performance of a simulation-based inference (SBI) model
    changes as a function of the number of posterior samples.

    The function trains a single SBI network on a fixed training dataset and
    evaluates its inference performance using progressively larger numbers of
    posterior samples. The inference procedure is repeated multiple times to
    assess the variability of the resulting performance metrics.

    Parameters
    ----------
    Model : object
        Model used to generate parameters and simulated observations. It must
        provide a ``sample_and_simulation`` method and a ``parameter_list``
        attribute.

    validation_snr : float or array-like
        Signal-to-noise ratio (SNR) used when generating both the training and
        test simulations.

    k_fold : int, optional
        Number of times the posterior-sampling experiment is repeated.
        The same trained network and test dataset are used for every
        repetition. Default is 5.

    max_samples : int, optional
        Maximum number of posterior samples generated per test observation.
        Must be at least 10. Default is 1,000.

    training_samples : int, optional
        Number of simulated samples used to train the SBI network.
        Default is 10,000.

    test_samples : int, optional
        Number of simulated samples in the shared test dataset used to
        evaluate the trained network. Default is 10,000.

    fidelity : int, optional
        Number of logarithmically spaced posterior-sample counts evaluated
        between 10 and ``max_samples``. Default is 5.

    Returns
    -------
    kFoldMetrics : list of dict
        Performance metrics from each repetition. Each dictionary contains
        the metrics evaluated for every posterior-sample count in ``N``.

    N : numpy.ndarray
        Array containing the posterior-sample counts used in the study.

    Raises
    ------
    ValueError
        If ``max_samples`` is smaller than 10.

    Notes
    -----
    The test dataset is generated once using a fixed random seed (2026), and
    the training dataset is generated once using a fixed random seed (45).
    Consequently, all repetitions use the same training data, test data, and
    trained SBI network.

    Unlike ``ParameterEval_TS``, the repetitions performed here do not retrain
    the network. They repeat posterior inference to quantify the variability
    associated with posterior sampling.

    The posterior-sample counts are logarithmically spaced using
    ``numpy.geomspace`` between 10 and ``max_samples``. Duplicate integer
    values introduced by rounding are removed with ``numpy.unique``.

    After all repetitions have been evaluated, ``PlotPerformance`` is called
    to visualize the collected metrics.

    Examples
    --------
    >>> metrics, sample_sizes = ParameterEval_PS(
    ...     Model=model,
    ...     validation_snr=10,
    ...     k_fold=5,
    ...     max_samples=1000,
    ...     training_samples=10_000,
    ...     test_samples=10_000,
    ...     fidelity=5
    ... )
    """

    if max_samples < 10:
        raise ValueError(f"max_samples must be at least 10, but received {max_samples}")

    print("~" * 20)
    print("We will perform a study on the number of posterior samples we might need")

    # Generate one shared test set
    test_rng = np.random.default_rng(2026)
    Params_test, Signals_test = Model.sample_and_simulation(test_samples, parallel=True, rng=test_rng, custom_snr=validation_snr)
    Par_test, Obs_test, _, _ = Helpers.Prep_data(Params_test, Signals_test, Model.parameter_list,Verbose=False)

    # Generate the training set and train one network
    train_rng = np.random.default_rng(45)
    Params_train, Signals_train = Model.sample_and_simulation(training_samples, parallel=True,rng=train_rng, custom_snr=Model.snr)
    Par_train, Obs_train, Names, _ = Helpers.Prep_data(Params_train, Signals_train, Model.parameter_list,Verbose=False)

    Network = SBI.Train_Network_gpu(Par_train, Obs_train,save=False)

    N = np.unique(np.geomspace(10, max_samples, fidelity).astype(int))
    kFoldMetrics = []

    for _ in tqdm.tqdm(range(k_fold),desc='Fold Number:', position=0, leave=True):
        AllMetrics = {}

        for posterior_samples in N:
            GuessParams = SBI.Infer(Network, Obs_test, Num_Samples=posterior_samples,show_tqdm=False)
            Metrics = Performance(Par_test, GuessParams, Model)
            for key, value in Metrics.items():
                AllMetrics.setdefault(key, []).append(value)

            del GuessParams

        kFoldMetrics.append(AllMetrics)

    PlotPerformance(kFoldMetrics, N,Names)

    return kFoldMetrics, N

def PlotPerformance(Metrics, N, Names):
    """
    Plot performance metrics as a function of sample count and identify
    convergence.

    The function aggregates performance metrics across repeated evaluations,
    computes the mean and standard error of the mean (SEM), and displays the
    resulting trends with error bars. Each metric is additionally assessed
    for convergence according to a metric-specific criterion.

    For coverage, values between 0.94 and 0.96 are considered acceptable.
    For all other metrics, convergence is assessed from the absolute
    logarithmic rate of change between consecutive sample counts, with values
    below 0.05 considered converged.

    Parameters
    ----------
    Metrics : list of dict
        Performance results from repeated evaluations, such as those returned
        by ``ParameterEval_TS`` or ``ParameterEval_PS``. Each dictionary must
        contain the same metric names and associate each metric with values
        evaluated at every sample count in ``N``.

        Metric values may either be one-dimensional, representing a single
        value per sample count, or two-dimensional, representing separate
        values for multiple model parameters.

    N : array-like
        Sample counts corresponding to the evaluations stored in ``Metrics``.
        These values are displayed on a logarithmic x-axis.

    Names : sequence of str
        Names of the model parameters. These are used in the legend when a
        metric contains separate values for multiple parameters.

    Returns
    -------
    None
        The function creates a Matplotlib figure and does not explicitly
        return a value.

    Notes
    -----
    Performance values are averaged across the repeated evaluations in
    ``Metrics``. Error bars represent the standard error of the mean (SEM).

    For the ``Coverage`` metric, values in the interval (0.94, 0.96) are
    marked as acceptable. A shaded region between 0.94 and 0.96 is displayed
    as a visual reference.

    For all other metrics, the logarithmic rate of change is approximated as

        d(log(metric)) / d(log(N)).

    A value is considered locally converged when the absolute magnitude of
    this quantity is smaller than 0.05. The reported point of convergence is
    the first sample count after which the convergence criterion remains
    satisfied for all subsequent sample counts.

    Converged or acceptable points are shown in green, while points that do
    not satisfy the corresponding criterion are shown in red.

    When metrics are parameter-specific, different marker shapes identify
    individual parameters and ``Names`` is used to construct the legend.

    Examples
    --------
    >>> metrics, sample_sizes = ParameterEval_TS(
    ...     Model=model,
    ...     validation_snr=10
    ... )
    >>> PlotPerformance(metrics, sample_sizes, model.parameter_list)
    """

    showlegend = False
    markers = ["o", "s", "^", "D", "v", "<", ">", "P", "X", "*", "h", "H", "p", "8", "d"]

    fig,axs = plt.subplots(2,3,figsize=(32,16))
    ax = axs.ravel()

    for a,k in zip(ax,Metrics[0].keys()):
        X = np.stack([np.array(M[k]) for M in Metrics])
        mean = X.mean(axis=0)

        sem = sp.stats.sem(X,axis=0)
        if(mean.ndim == 2): 
            for y, yerr in zip(mean.T, sem.T):
                a.errorbar(N, y, yerr=yerr,lw=3,alpha=0.5,c='gray')
        else:
            a.errorbar(N, mean, yerr=sem,lw=3,alpha=0.5,c='gray')

        

        if(k=='Coverage'):
            a.fill_between([N[0],N[-1]],[0.94,0.94],[0.96,0.96],alpha=0.5,color='gray')
            mask = (mean < 0.96) & (mean >0.94)

            converged = np.all(mask,axis=tuple(range(1, mean.ndim)))
            idx = np.flatnonzero(converged)
            idx = idx[0] if idx.size else None
        else:
            delta = np.log(mean[1:]) - np.log(mean[:-1])
            delta_N = np.log(N[1:]) - np.log(N[:-1])
            
            derror_dN = np.concatenate(
                [np.ones_like(mean[:1]), (delta.T / delta_N).T],
                axis=0
            )
            
                
            mask = np.abs(derror_dN) < 0.05
        
        converged = np.all(mask,axis=tuple(range(1, derror_dN.ndim)))
        true_idx = np.flatnonzero(converged)
        idx = next(
            (i for i in true_idx if np.all(converged[i:])),
            None
        )

        N_shaped = np.asarray(N).reshape(
            (len(N),) + (1,) * (mean.ndim - 1)
        )
        
        N_grid = np.broadcast_to(N_shaped, mean.shape)
        if mean.ndim == 1:
            a.plot(
                N_grid[mask],
                mean[mask],
                c="green",
                marker="o",
                ls="None",
            )
            a.plot(
                N_grid[~mask],
                mean[~mask],
                c="red",
                marker="o",
                ls="None",
            )

        else:
            parameter_colors = plt.cm.tab20(np.linspace(0, 1, mean.shape[1]))
            markers = ["o", "s", "^", "D", "v", "<", ">", "P", "X", "*"]
            for i in range(mean.shape[1]):
                marker = markers[i % len(markers)]
                a.plot(
                    N[mask[:, i]],
                    mean[mask[:, i], i],
                    c="green",
                    marker=marker,
                    ls="None",
                    label=Names[i],
                )
                a.plot(
                    N[~mask[:, i]],
                    mean[~mask[:, i], i],
                    c="red",
                    marker=marker,
                    ls="None",
                )
            if(not showlegend):
                a.legend()
                showlegend = True
    
        a.semilogx()

        
        if idx is not None:
            a.set_title(k+ f' (Point of convergence: {N[idx]})')
        else:
            a.set_title(k+ f' (Not converged/good coverage)')


def Performance(TrueParams, PosteriorSamples, Model, Mode_eval=False):
    """
    Evaluate parameter-estimation and signal-reconstruction performance from
    posterior samples.

    The function compares posterior parameter estimates against known true
    parameters and computes metrics describing point-estimation accuracy,
    posterior coverage, posterior width, and reconstructed-signal quality.

    By default, posterior means are used as point estimates. Optionally,
    histogram-based posterior modes can also be estimated and evaluated.

    Parameters
    ----------
    TrueParams : torch.Tensor
        True parameter values for the test observations. The expected shape is
        ``(n_observations, n_parameters)``. The tensor is converted to a NumPy
        array internally.

    PosteriorSamples : array-like
        Posterior parameter samples. The expected shape is
        ``(n_posterior_samples, n_observations, n_parameters)``.

        The first dimension contains posterior draws, the second corresponds
        to test observations, and the third corresponds to model parameters.

    Model : object
        Model associated with the inferred parameters. It must provide a
        ``simulation`` method and a ``compartments`` attribute.

        The ``simulation`` method is used to reconstruct signals from both the
        inferred and true parameter values.

    Mode_eval : bool, optional
        If ``True``, additionally estimate the mode of each marginal posterior
        distribution using ``histogram_mode`` and compute its normalized point
        error. At least 50 posterior samples are required when this option is
        enabled. Default is ``False``.

    Returns
    -------
    metrics : dict
        Dictionary containing the calculated performance metrics.

        ``"Point error"``
            Mean absolute error of the posterior-mean parameter estimates,
            normalized by the range of each true parameter.

        ``"Coverage"``
            Fraction of true parameter values contained within the 95%
            posterior credible interval, computed separately for each
            parameter.

        ``"Width"``
            Mean width of the 95% posterior credible interval, normalized by
            the range of each true parameter.

        ``"SignalRMSE"``
            Mean root-mean-square error between signals reconstructed from the
            posterior-mean parameters and signals generated from the true
            parameters.

        ``"SignalCorr"``
            Mean correlation between the reconstructed and true signals.

        ``"Point error (mode)"``
            Normalized parameter error obtained using histogram-based posterior
            modes. This entry is included only when ``Mode_eval=True``.

    Raises
    ------
    ValueError
        If ``Mode_eval=True`` and fewer than 50 posterior samples are
        available.

    Notes
    -----
    The 95% posterior credible interval is defined using the 2.5th and 97.5th
    percentiles of the posterior samples.

    Parameter errors and credible-interval widths are normalized independently
    for each parameter using

        max(TrueParams) - min(TrueParams).

    This makes the parameter-based metrics dimensionless and facilitates
    comparison between parameters with different numerical scales.

    Before reconstructing signals, the omitted compartment fraction is
    recovered as one minus the sum of the explicitly inferred compartment
    fractions. The reconstructed parameter arrays are then passed to
    ``Model.simulation`` with ``custom_snr=None``.

    ``SignalRMSE`` measures absolute reconstruction disagreement, whereas
    ``SignalCorr`` measures similarity in signal shape after subtracting the
    mean of each signal.

    Examples
    --------
    >>> metrics = Performance(
    ...     TrueParams=true_parameters,
    ...     PosteriorSamples=posterior_samples,
    ...     Model=model
    ... )
    >>> metrics["Coverage"]
    array([...])

    To additionally evaluate posterior modes:

    >>> metrics = Performance(
    ...     TrueParams=true_parameters,
    ...     PosteriorSamples=posterior_samples,
    ...     Model=model,
    ...     Mode_eval=True
    ... )

    """
    TrueParams = TrueParams.numpy()
    N = PosteriorSamples.shape[1]
    NumSamples = PosteriorSamples.shape[0]
    #Point error - evaluated with mean
    Err_mean = (abs(PosteriorSamples.mean(axis=0)-TrueParams)/(TrueParams.max(axis=0)-TrueParams.min(axis=0))).mean(axis=0)
    #Point error - evaluated with histo
    lower, upper = np.quantile(PosteriorSamples, [0.025, 0.975], axis=0)
    Coverage = np.sum((lower < TrueParams) &  (TrueParams < upper),axis=0) / N
    #Width
    Width = ((upper - lower)/(TrueParams.max(axis=0)-TrueParams.min(axis=0))).mean(axis=0)
    #Signal reconstruction with mean 
    Reconstruct_Paramters = PosteriorSamples.mean(axis=0).numpy()
    Reconstruct_Paramters = np.concatenate([
        (1 - np.sum(Reconstruct_Paramters[:, :(len(Model.compartments) - 1)], axis=1))[:, None],
        Reconstruct_Paramters
    ], axis=1)

    Reconstruct_TrueParamters = np.concatenate([
        (1 - np.sum(TrueParams[:, :(len(Model.compartments) - 1)], axis=1))[:, None],
        TrueParams
    ], axis=1)

    GuessSignals = Model.simulation(Reconstruct_Paramters,custom_snr = None)

    TrueSignals  = Model.simulation(Reconstruct_TrueParamters,custom_snr = None)
    SignalRMSE = np.sqrt(((TrueSignals - GuessSignals)**2).mean(axis=1)).mean()
    T = TrueSignals - TrueSignals.mean(axis=1, keepdims=True)
    G = GuessSignals - GuessSignals.mean(axis=1, keepdims=True)
    SignalCorr = (np.sum(T * G, axis=1) / np.sqrt(np.sum(T**2, axis=1) * np.sum(G**2, axis=1))).mean()
    if(Mode_eval):
        if NumSamples < 50:
            raise ValueError(
                f"Number of samples must exceed 50 (Currently {NumSamples})."
            )    
        Histo_est = np.array([[histogram_mode(PosteriorSamples[:, j, i])  
                          for i in range(PosteriorSamples.shape[2])]
                          for j in range(N)])
        Err_histo = (abs(Histo_est-TrueParams)/(TrueParams.max(axis=0)-TrueParams.min(axis=0))).mean(axis=0)
        return {
            "Point error": Err_mean,
            "Coverage": Coverage,
            "Width": Width,
            "SignalRMSE": SignalRMSE,
            "SignalCorr": SignalCorr,
            "Point error (mode)": Err_histo
        }
    else:
        return {
            "Point error": Err_mean,
            "Coverage": Coverage,
            "Width": Width,
            "SignalRMSE": SignalRMSE,
            "SignalCorr": SignalCorr
        }

